/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jxvikpmfcpzyjjksmhnd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dmlrcG1mY3B6eWpqa3NtaG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNzA3NDksImV4cCI6MjA3NTc0Njc0OX0.Y9s2e1Z8c0UTwUbzQ7u08-975t8vqhlHL-WmYyJ_sjU"